### ISSUE TITLE
Repositories is initially hidden on Repositories preference page

### ISSUE THREAD

**Issue by cdwilson** [eclipse-embed-cdt-move/eclipse-plugins#375]
For some reason, Repositories is always blank when I first launch MCU packages preferences, and then I have to click "Edit" button for it to display the repository line.

![2020-01-23_09-31-45 (1)](https://user-images.githubusercontent.com/14631/73010915-2a42dd00-3dc8-11ea-8c84-1a925e78f1f8.gif)

```
Eclipse IDE for GNU ARM & RISC-V C/C++ Developers

Version: 2019-12 (4.14.0)
Build id: 20200115-1949
```

**Comment by ilg-ul** [comment]
Could you try with a fresh workspace too?

That version is from Eclipse, the plug-ing have their own versions.

**Comment by ilg-ul** [comment]
I cannot reproduce the issue.

I installed a fresh Eclipse from 20200115-1949-gnumcueclipse-4.7.1-2019-12-R-macosx.cocoa.x86_64.tar.gz, with a fresh workspace, went straight to the Preferences page and URL is there.

I suggest you retry in the same conditions. On macOS, be sure you remove the `com.apple.quarantine` attribute, otherwise the behaviour may be unexpected.

**Comment by cdwilson** [comment]
I retried with a fresh install and a fresh workspace and everything works as expected (I can't reproduce the issue seen previously).

**Comment by ilg-ul** [comment]
Ok, glad it works for you now.
